USE [CS6-3]

/// Propietario///


CREATE TABLE PROPIETARIO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
	DNI NVARCHAR(10) UNIQUE,
    NOMBRES NVARCHAR(100),
    APELLIDOS NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    DIRECCION NVARCHAR(200)
);


CREATE PROCEDURE InsertarPropietario
    @DNI NVARCHAR(10),
    @Nombres NVARCHAR(100),
    @Apellidos NVARCHAR(100),
    @Correo NVARCHAR(100),
    @Telefono NVARCHAR(20),
    @Direccion NVARCHAR(200)
AS
BEGIN
    INSERT INTO PROPIETARIO (DNI, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION)
    VALUES (@DNI, @Nombres, @Apellidos, @Correo, @Telefono, @Direccion);
END










/// Vehiculo ///



CREATE TABLE VEHICULO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
	PLACA NVARCHAR(8) UNIQUE,
    VALOR DECIMAL(10,2), 
    AÑO INT,
    CILINDRAJE INT, 
    MODELO NVARCHAR(50), 
	COLOR NVARCHAR(100),
	ID_PROPIETARIO INT FOREIGN KEY REFERENCES PROPIETARIO(ID)
);


SELECT * FROM PROPIETARIO
SELECT * FROM VEHICULO